### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by miel775** [fdnd-task/fix-the-flow-interactive-website#5]
Als gebruiker wil ik filteren op _schaduw/half schaduw/zon_ zodat _het overzichtelijk wordt._

**Comment by miel775** [comment]
![thumbnail_IMG_2321](https://github.com/user-attachments/assets/5798ac0b-c7a4-4769-b4e0-c870aea8e240)

**Comment by miel775** [comment]
het is maandag

**Comment by KoopReynders** [comment]
Dit issue moet je in eigen repo aanmaken!
