### ISSUE TITLE
Figma design light dark mode theme/button

### ISSUE THREAD

**Issue by Mikiyas-hs** [fdnd-task/fix-the-flow-interactive-website#6]
![image](https://github.com/user-attachments/assets/f394c7b7-d8eb-4457-b47c-95051831b943)

**Comment by KoopReynders** [comment]
Issues moet je aan je eigen repo hangen!
-

**Comment by Mikiyas-hs** [comment]
Sorry ik dacht ik in me eigen repo de issue had geplaatst ik zie nu pas dat
het in de fdnd repo was

Op zo 8 dec 2024 om 14:51 schreef Koop Reynders ***@***.***>

**Comment by KoopReynders** [comment]
Ha. Gebeurt heel vaak!
